#
# Makefile for optimizer
#
# src/backend/gporca/libgpopt/src/hints/Makefile
#

subdir = src/backend/gporca/libgpopt/src/hints
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS        = CPlanHint.o CScanHint.o CRowHint.o CJoinHint.o CJoinTypeHint.o CHintUtils.o

include $(top_srcdir)/src/backend/common.mk

